apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simple-nodejs-app-gst1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simple-nodejs-app-gst1
    app.kubernetes.io/part-of: nodejs-users
  name: simple-nodejs-app-gst1
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: simple-nodejs-app-gst1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: simple-nodejs-app-gst1
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jftf-tenant/nodejs-users/simple-nodejs-app-gst1@sha256:773cc1180afcfbc7635fd9cfd69c236b50d20547e7090ac5e46216a8207a3a6f
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
